### ISSUE TITLE
The latest version (0.28) of Bitcoin node is not supported

### ISSUE THREAD

**Issue by xuzhitong** [CounterpartyXCP/addrindexrs#28]
When I deployed the latest version (v0.28.0) of the Bitcoin node, synchronized to the latest block, and started addrindexrs, I found that the service panicked and the exception was caused by 'bulk_index out of range'. The code position where the exception stack was thrown was line 123 of bulk.rs, which is:
```
        let block: Block = deserialize(&blob[start as usize..end as usize])
            .chain_err(|| format!("failed to parse block at {}..{}", start, end))?;
```
This is an exception related to block data parsing, so I suspect that the Bitcoin versions of the node and the service are incompatible. I checked the bitcoin-core dynamic library version used by the service and found that it was 0.21.0, so I rolled back the Bitcoin node version to this version and reindexed (which took 2 days), and then started the service and found that it was normal.  
I think there must be some incompatibility between Bitcoin 0.21 and 0.28, but I don't know which parts

**Comment by adamkrellenstein** [comment]
Yeah, addrindexrs is unmaintained. we're about to remove it from counterparty. but nice catch!

**Comment by adamkrellenstein** [comment]
actually looks like it's not a version issue. not going to investigate though :/
