### ISSUE TITLE
Range end index XXXXXX out of range

### ISSUE THREAD

**Issue by cuongd86** [CounterpartyXCP/addrindexrs#29]
**Describe the Problem**
I've have installed bitcoin core v28.0 and then I run addrindexrs with this command

`cargo run --release -- -vvv --timestamp --conf /path/to/addrindexrs/config.toml`

1. I see this log entries
`cargo[123601]:     index_batch_size: 100,
cargo[123601]:     bulk_index_threads: 10,
cargo[123601]:     blocktxids_cache_size: 10485760,
cargo[123601]: }
cargo[123601]: INFO - NetworkInfo { version: 280000, subversion: "/Satoshi:28.0.0/" }
cargo[123601]: INFO - BlockchainInfo { chain: "main", blocks: 874974, headers: 874974, bestblockhash: "xxxxxxxxxxxxxx", pruned: false, initialblockdownload: false }
cargo[123601]: DEBUG - opening DB at "/path/to/addrindexrs_db/mainnet"
cargo[123601]: INFO - listing block files at "/path/to/bitcoind/blocks/blk*.dat"
cargo[123601]: INFO - indexing 4665 blk*.dat files
cargo[123601]: DEBUG - found 0 indexed blocks`

2. After that, the error happens:
 `cargo[123601]: thread 'bulk_index' panicked at src/bulk.rs:123:45:
cargo[123601]: range end index 3551347787 out of range for slice of length 134047602
cargo[123601]: stack backtrace:
cargo[123601]:    0: rust_begin_unwind
cargo[123601]:    1: core::panicking::panic_fmt
cargo[123601]:    2: core::slice::index::slice_end_index_len_fail
cargo[123601]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
`

Config.toml just cointains 

`daemon_rpc_addr = 127.0.0.1: 8332"
daemon_p2p_addr = "127.0.0.1: 8333"
cookie = "daemonuser:daemonpass"
db_dir = "path/to/addrindexrs_db"
daemon_dir = "path/to/bitcoind/"
network = "bitcoin"
electrum_rpc_addr = "127.0.0.1:50001"
log_filters = "INFO"`

I checked the integrity of the blk*.dat files by this command
`bitcoin-cli -datadir=/path/to/bitcoind/ verifychain 3 6`

the result is true. it confirms that my blockchain data is not corrupted and is consistent.

What should I do to solve this error?

**Comment by adamkrellenstein** [comment]
this software is unmaintained. will archive the repo to make that clear. we're in the process of removing the dependency from Counterparty Core permanently
